# -*- coding: utf-8 -*-
"""Untitled37.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17lAaDskGGC6UrQVfeAp7vm8pjCphZHN2
"""

from setuptools import setup, find_packages

setup(
    name='emotion_classifier_pkg',  # Choose a unique name for your package
    version='0.1.0',
    author='[Allan Stalker]',
    author_email='[astalker.ieu2022@student.ie.edu]',
    description='A CLI tool to predict emotion from tweet text for a Kaggle competition.',
    long_description=open('README.md').read() if Path('README.md').exists() else '',
    long_description_content_type='text/markdown',
    url='https://github.com/yourusername/yourproject', # Replace with your GitHub repo URL
    packages=find_packages(where='.'), # find_packages will find 'emotion_classifier'
    package_dir={'': '.'}, # Tells find_packages that packages are under the root
    install_requires=[
        'torch>=1.9.0',         # Or the version you used for training
        'transformers>=4.10.0', # Or the version you used
        'scikit-learn>=0.24.0',
        'pandas>=1.0.0',
        'nltk>=3.6.0',
        'joblib>=1.0.0',
        'requests>=2.25.0',     # For downloading model assets
    ],
    entry_points={
        'console_scripts': [
            'inference=emotion_classifier.cli:main',
        ],
    },
    classifiers=[
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: MIT License', # Or your chosen license
        'Operating System :: OS Independent',
    ],
    python_requires='>=3.7',
    include_package_data=False, # MANIFEST.in is not strictly needed if not bundling assets initially
)